server:
  port: 8082
  servlet:
    context-path: /v1
spring:
  main:
    allow-bean-definition-overriding: false
  datasource:
    url: jdbc:mysql://localhost:3306/app_maranata?createDatabaseIfNotExist=true&serverTimezone=Europe/Rome
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace