server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/florinivan/be_gestione_chiesa
          search-paths:
          - '*service' 
          #username: 
          #passphrase: ******
          
          